// Generated by CoffeeScript 1.9.2
(function() {
  var CusTest;

  CusTest = (function() {
    function CusTest() {
      this.cases = [];
    }

    CusTest.prototype.addCase = function(c) {
      return this.cases.push(c);
    };

    CusTest.prototype.test = function() {
      return YUI({
        logInclude: {
          TestRunner: true
        }
      }).use('test', 'test-console', (function(_this) {
        return function(y) {
          var c, i, len, ref;
          ref = _this.cases;
          for (i = 0, len = ref.length; i < len; i++) {
            c = ref[i];
            YUITest.TestRunner.add(new YUITest.TestCase(c));
          }
          new y.Test.Console({
            newestOnTop: false,
            filters: {
              info: false,
              pass: true,
              fail: true
            }
          }).render('#log');
          YUITest.TestRunner.run();
        };
      })(this));
    };

    return CusTest;

  })();

  window.CusTest = CusTest;

}).call(this);
